
package proj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSend", targetNamespace = "http://proj/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerSend {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTable", targetNamespace = "http://proj/", className = "proj.UpdateTable")
    @ResponseWrapper(localName = "updateTableResponse", targetNamespace = "http://proj/", className = "proj.UpdateTableResponse")
    @Action(input = "http://proj/ServerSend/updateTableRequest", output = "http://proj/ServerSend/updateTableResponse")
    public String updateTable(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
