
package proj;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerSendService", targetNamespace = "http://proj/", wsdlLocation = "http://192.168.0.96:1007/proj/PAYMENT_SERVICES?wsdl")
public class ServerSendService
    extends Service
{

    private final static URL SERVERSENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERSENDSERVICE_EXCEPTION;
    private final static QName SERVERSENDSERVICE_QNAME = new QName("http://proj/", "ServerSendService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.96:1007/proj/PAYMENT_SERVICES?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERSENDSERVICE_WSDL_LOCATION = url;
        SERVERSENDSERVICE_EXCEPTION = e;
    }

    public ServerSendService() {
        super(__getWsdlLocation(), SERVERSENDSERVICE_QNAME);
    }

    public ServerSendService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERSENDSERVICE_QNAME, features);
    }

    public ServerSendService(URL wsdlLocation) {
        super(wsdlLocation, SERVERSENDSERVICE_QNAME);
    }

    public ServerSendService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERSENDSERVICE_QNAME, features);
    }

    public ServerSendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerSendService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerSend
     */
    @WebEndpoint(name = "ServerSendPort")
    public ServerSend getServerSendPort() {
        return super.getPort(new QName("http://proj/", "ServerSendPort"), ServerSend.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerSend
     */
    @WebEndpoint(name = "ServerSendPort")
    public ServerSend getServerSendPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://proj/", "ServerSendPort"), ServerSend.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERSENDSERVICE_EXCEPTION!= null) {
            throw SERVERSENDSERVICE_EXCEPTION;
        }
        return SERVERSENDSERVICE_WSDL_LOCATION;
    }

}
